ekyna_demo_brand_admin_home:
    path: ""
    defaults: { _controller: "ekyna_demo.brand.controller:homeAction" }
    methods: [GET]

ekyna_demo_brand_admin_list:
    path: /list
    defaults: { _controller: "ekyna_demo.brand.controller:listAction" }
    methods: [GET|POST]

ekyna_demo_brand_admin_new:
    path: /new
    defaults: { _controller: "ekyna_demo.brand.controller:newAction" }
    methods: [GET|POST]

ekyna_demo_brand_admin_show:
    path: /{brandId}/show
    defaults: { _controller: "ekyna_demo.brand.controller:showAction" }
    methods: [GET]
    requirements:
        brandId: \d+

ekyna_demo_brand_admin_edit:
    path: /{brandId}/edit
    defaults: { _controller: "ekyna_demo.brand.controller:editAction" }
    methods: [GET|POST]
    requirements:
        brandId: \d+

ekyna_demo_brand_admin_remove:
    path: /{brandId}/remove
    defaults: { _controller: "ekyna_demo.brand.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        brandId: \d+
