ekyna_demo_smartphone_admin_home:
    path: ""
    defaults: { _controller: "ekyna_demo.smartphone.controller:homeAction" }
    methods: [GET]

ekyna_demo_smartphone_admin_list:
    path: /list
    defaults: { _controller: "ekyna_demo.smartphone.controller:listAction" }
    methods: [GET|POST]

ekyna_demo_smartphone_admin_new:
    path: /new
    defaults: { _controller: "ekyna_demo.smartphone.controller:newAction" }
    methods: [GET|POST]

ekyna_demo_smartphone_admin_show:
    path: /{smartphoneId}/show
    defaults: { _controller: "ekyna_demo.smartphone.controller:showAction" }
    methods: [GET]
    requirements:
        smartphoneId: \d+

ekyna_demo_smartphone_admin_edit:
    path: /{smartphoneId}/edit
    defaults: { _controller: "ekyna_demo.smartphone.controller:editAction" }
    methods: [GET|POST]
    requirements:
        smartphoneId: \d+

ekyna_demo_smartphone_admin_tinymce:
    path: /{smartphoneId}/tinymce
    defaults: { _controller: "ekyna_demo.smartphone.controller:tinymceAction", field: html }
    methods: [GET]
    requirements:
        smartphoneId: \d+

#ekyna_demo_smartphone_admin_content:
#    path: /{smartphoneId}/content
#    defaults: { _controller: "ekyna_demo.smartphone.controller:contentShowAction" }
#    methods: [GET]
#    requirements:
#        smartphoneId: \d+
#
#ekyna_demo_smartphone_admin_content_edit:
#    path: /{smartphoneId}/content/edit
#    defaults: { _controller: "ekyna_demo.smartphone.controller:contentEditAction" }
#    methods: [GET|POST]
#    requirements:
#        smartphoneId: \d+

ekyna_demo_smartphone_admin_remove:
    path: /{smartphoneId}/remove
    defaults: { _controller: "ekyna_demo.smartphone.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        smartphoneId: \d+

ekyna_demo_smartphone_variant_admin:
    resource: "smartphone_variant.yml"
    prefix:   /{smartphoneId}/variants
