#ekyna_demo_smartphone_variant_admin_home:
#    path: ""
#    defaults: { _controller: "ekyna_demo.smartphone.controller:homeAction" }
#    methods: [GET]
#    requirements:
#        smarpthoneId: \d+

#ekyna_demo_smartphone_variant_admin_list:
#    path: /list
#    defaults: { _controller: "ekyna_demo.smartphone.controller:listAction" }
#    methods: [GET|POST]
#    requirements:
#        smarpthoneId: \d+

ekyna_demo_smartphone_variant_admin_new:
    path: /new
    defaults: { _controller: "ekyna_demo.smartphone_variant.controller:newAction" }
    methods: [GET|POST]
    requirements:
        smartphoneId: \d+

ekyna_demo_smartphone_variant_admin_show:
    path: /{smartphoneVariantId}/show
    defaults: { _controller: "ekyna_demo.smartphone_variant.controller:showAction" }
    methods: [GET]
    requirements:
        smartphoneId: \d+
        smartphoneVariantId: \d+

ekyna_demo_smartphone_variant_admin_edit:
    path: /{smartphoneVariantId}/edit
    defaults: { _controller: "ekyna_demo.smartphone_variant.controller:editAction" }
    methods: [GET|POST]
    requirements:
        smartphoneId: \d+
        smartphoneVariantId: \d+

ekyna_demo_smartphone_variant_admin_remove:
    path: /{smartphoneVariantId}/remove
    defaults: { _controller: "ekyna_demo.smartphone_variant.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        smartphoneId: \d+
        smartphoneVariantId: \d+
