ekyna_demo_store_admin_home:
    path: ""
    defaults: { _controller: "ekyna_demo.store.controller:homeAction" }
    methods: [GET]

ekyna_demo_store_admin_list:
    path: /list
    defaults: { _controller: "ekyna_demo.store.controller:listAction" }
    methods: [GET|POST]

ekyna_demo_store_admin_new:
    path: /new
    defaults: { _controller: "ekyna_demo.store.controller:newAction" }
    methods: [GET|POST]

ekyna_demo_store_admin_show:
    path: /{storeId}/show
    defaults: { _controller: "ekyna_demo.store.controller:showAction" }
    methods: [GET]
    requirements:
        storeId: \d+

ekyna_demo_store_admin_edit:
    path: /{storeId}/edit
    defaults: { _controller: "ekyna_demo.store.controller:editAction" }
    methods: [GET|POST]
    requirements:
        storeId: \d+

ekyna_demo_store_admin_remove:
    path: /{storeId}/remove
    defaults: { _controller: "ekyna_demo.store.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        storeId: \d+
