home:
    pattern: /
    defaults:
        _controller: EkynaDemoBundle:Demo:home
        _cms:
            name: Accueil
            menu: true
    requirements:
        _method: GET

about:
    pattern: /about
    defaults:
        _controller: EkynaDemoBundle:Demo:default
        _cms:
            name: À propos
            menu: true
            footer: true
            locked: false
            advanced: true
    requirements:
        _method: GET

case_studies:
    path: /about/case-studies
    defaults:
        _controller: EkynaDemoBundle:Demo:default
        _cms:
            name: Étude de cas
            parent: about
            menu: true
            locked: false
            advanced: true
    requirements:
        _method: GET

expertise:
    path: /about/expertise
    defaults:
        _controller: EkynaDemoBundle:Demo:default
        _cms:
            name: Expertise
            parent: about
            menu: true
            locked: false
            advanced: true
    requirements:
        _method: GET

contact:
    pattern: /contact
    defaults:
        _controller: EkynaDemoBundle:Demo:contact
        _cms:
            name: Contact
            menu: true
            footer: true
    requirements:
        _method: GET|POST
