ekyna_demo_catalog_index:
    path: ""
    defaults:
        _controller: EkynaDemoBundle:Catalog:index
    methods: [GET]
    options:
        _cms:
            name: Catalogue
            menus: [main, footer]
            advanced: true

ekyna_demo_catalog_category:
    path: /{categorySlug}
    defaults:
        _controller: EkynaDemoBundle:Catalog:category
    methods: [GET]
    requirements:
        categorySlug: "[a-z0-9-/]+"
    options:
        _cms:
            parent: ekyna_demo_catalog_index

ekyna_demo_catalog_product:
    path: /{categorySlug}/{productSlug}.html
    defaults:
        _controller: EkynaDemoBundle:Catalog:product
    methods: [GET|POST]
    requirements:
        categorySlug: "[a-z0-9-]+"
        productSlug: "[a-z0-9-]+"
    options:
        _cms:
            parent: ekyna_demo_catalog_index
