test_test:
    path: /test
    defaults:
        _controller: EkynaDemoBundle:Test:test
    methods: [GET]

test_home:
    path: /home
    defaults:
        _controller: EkynaDemoBundle:Test:home
    methods: [GET]

test_part_one:
    path: /part-one
    defaults:
        _controller: EkynaDemoBundle:Test:partOne
    methods: [GET]

test_part_two:
    path: /part-two
    defaults:
        _controller: EkynaDemoBundle:Test:partTwo
    methods: [GET]

test_part_three:
    path: /part-three
    defaults:
        _controller: EkynaDemoBundle:Test:partThree
    methods: [GET]

test_purge:
    path: /test-purge
    defaults:
        _controller: EkynaDemoBundle:Test:purge
    methods: [GET]
