schemas:
    smartphone:
        title: Produit
        groups:
            general:
                title: Général
                characteristics:
                    reference:
                        title: Référence
                        type: text
                    color:
                        title: Couleur
                        type: choice
                    size:
                        title: Taille de l'écran
                        type: number
                    brand:
                        title: Marque
                        type: virtual
                        parameters:
                            property_path: smartphone.brand.title
            network:
                title: Réseaux
                characteristics:
                    wifi:
                        title: WiFi
                        type: boolean
